#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

#borders
bspc config focused_border_color "#44475a"
bspc config normal_border_color "#1f222b"
bspc config border_width 2
bspc config borderless_monocle true

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

#gaos
bspc config gapless_monocle false
bspc config window_gap 8
#bspc config split_ratio 0.52

#rules
bspc rule -a pavucontrol state=floating

~/.config/polybar/launch.sh &
nitrogen --restore &
picom &
polybar &
