require("settings")
require("keymaps")
require("plugins.packer")
-- Plugins
require("plugins.nord")
require("plugins.bufferline")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.nvim-tree")
require("plugins.autopairs")
require("plugins.startup")
require("plugins.nvim-cmp")
require("plugins.colorizer")
require("plugins.formatting")
require("plugins.lsp")
require("plugins.indent-blankline")
